# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R


os:
  - linux

sudo: false	
cache: packages
use_bioc: true
bioc_required: true
warnings_are_errors: false

r:
  - devel

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
